# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# --- NUEVO: Añade esta sección para programar la función ---
#[functions.dailyChecks]
#  # Expresión Cron: "Minuto Hora Día Mes DíaDeLaSemana"
#  # "0 8 * * *" significa: a las 8:00 AM, todos los días.
#  schedule = "0 8 * * *"